Cuis-Smalltalk/Cuis-Smalltalk-Dev

- Packages/SqueakCompatibility.pck.st
- README.md
Hi Juan,
I added more Squeak compatibility methods and fixed the shell scripts for Getting Started from the command line.
Cheers,
Bernhard
> More Squeak compatibility methods

- CoreUpdates/2526-CuisCore-BernhardPieber-2015Oct11-11h48m-bp.1.cs.st
Hi Juan,
I added resize commands to the SystemWindow menu, top, left, bottom, right, top left, top right, bottom left, bottom right.
Maybe this is useful for others, too.
Cheers,
Bernhard
> Add resize commands to SystemWindow menu

- CoreUpdates/2584-ScrollBarColorInTheme-LucianoEstebanNotarfrancesco-2015Nov18-01h20m-len.1.cs.st
- CoreUpdates/2585-DeleteWindowRemoveHalo-LucianoEstebanNotarfrancesco-2015Nov18-01h23m-len.1.cs.st
- CoreUpdates/2586-LayoutMorphConservativeFix-LucianoEstebanNotarfrancesco-2015Nov18-01h25m-len.1.cs.st
- CoreUpdates/2587-SystemWindowDontGoFarBehind-LucianoEstebanNotarfrancesco-2015Nov18-02h31m-len.1.cs.st
- CoreUpdates/2588-RemoveLeftover-LucianoEstebanNotarfrancesco-2015Nov18-03h17m-len.1.cs.st
- CoreUpdates/2589-MessageNamesRemoveHardcodedColor-LucianoEstebanNotarfrancesco-2015Nov18-06h17m-len.1.cs.st
- CoreUpdates/2590-FunctionGraphMorphDontDrawOutside-LucianoEstebanNotarfrancesco-2015Nov18-07h11m-len.1.cs.st
I did a new patch for LayoutMorph that doesn't affect the old behaviour (the separate thing).
Also I fixed a couple of things related to window iteration as alt-tab in windows. In Cuis I found this is already coded in HandMorph and works fine in my linux with alt-> and alt-<
> a few fixes and enh

- Packages/ClassCommentBrowser.pck.st
- Packages/TerseGuide.pck.st
This is needed to make window open right after recent Layout/LayoutSpec changes.
> add explicit 'LayoutSpec useAll' in #buildMorphicWindow

- CoreUpdates/2697-TheWorldMenu-OpenGroupSimplify-PhilBellalouna-2016Feb28-09h56m-pb.1.cs.st
Simplify TheWorldMenu open group per our mailing list discussion.
> Streamline TheWorldMenu open group

- Packages/TerseGuide.pck.st
> add '::' to Syntax topic

- CoreUpdates/2985-WorldState-ivars-PhilBellalouna-2016Oct30-17h27m-pb.1.cs.st
- CoreUpdates/2986-Collection-statistics-PhilBellalouna-2016Nov21-12h50m-pb.1.cs.st
Performance enhancements to Morphic and Collections
> Performance enhancements

- CoreUpdates/2996-CuisCore-BernhardPieber-2016Dec06-20h13m-bp.1.cs.st
Allows resizing and moving SystemWindows using ResizeMorph, a grid to select where on the desktop the SystemWindow should be positioned.
> Add SystemWindow resize… using ResizeMorph

- CoreUpdates/3025-Point-immutable-PhilBellalouna-2017Jan03-pb.1.cs.st
- CoreUpdates/3026-Point-immutable-optimizations-PhilBellalouna-2017Jan03-pb.1.cs.st
If this is acceptable, next I'll start migrating the 0@0 calls in the image...
> Adapt Point immutable changes to backtick (i.e. `0@0`) syntax

- Documentation/FileSystemOperations.md
- Documentation/GettingStarted.md
- Explain the name of Cuis
- Explain FileMan adaptation in 2015
> Two documenation updates March 2018

- Documentation/AdditionalPackagesForCuis.md
Explain how to only load some of the packages in the 'packages' subfolder
Feature require: 'Sound'.
Feature require: 'WebClient'.
Feature require: 'JSON'.
> Feature require: 'Sound'

- Documentation/BestPractices.md
Hi,
I thought it was worth to summarize the best practices of cuis into a document. This is supposed to
be a WIP document to document for newbies and not yet-fully-understanding people best practices
and some design decisions.
Cheers
> Add basic best practices document

- Packages/TerseGuide.pck.st
This section demonstrates how to open a Method Browser with a custom list of methods. Right now it contains just one example, with something I found useful (finding all methods from a category) but we can start to grow this section with more powerful examples.
> Add a new section about Custom Browsers to the Terse Guide

- Packages/BaseImageTests.pck.st
Sending the corresponding Cuis-Core changeset by email!
> Support for quoted expressions in the extract method refactoring

- Packages/DevTools/Tools-Finder.pck.st
I don't know if you would want to include the Cuis Finder like this in Cuis distro. But if you do, then you have a merge button here.
> Include Finder as package

- Packages/Features/Printf.pck.st
as title says, just adds one file to move Printf inside Cuis-Smalltalk-Dev
bye
Nicola
> added Printf.pck.st package

- Documentation/HitchHikersCompiler.md
adds Cuis specific procedures to the HitchHikers guide to the compiler.
> Added Cuis specific procedures.

- CoreUpdates/5033-PackageInstaller-MarianoMontone-2022Jan03-21h00m-MM.001.cs.st
- CoreUpdates/5034-PackageInstallerCategory-MarianoMontone-2022Jan03-21h32m-MM.001.cs.st
- CoreUpdates/5035-PackageDownloaderMenu-MarianoMontone-2022Jan03-22h10m-MM.001.cs.st
- CoreUpdates/5036-PackageToolsWindowsColors-MarianoMontone-2022Jan03-22h29m-MM.001.cs.st
- Packages/Tools/PackageDownloader.pck.st
- Packages/Tools/PackageDownloaderUtils.pck.st
This pull request contains the integration of Package Installer and Downloader to Cuis.
I've added Package Installer directly to Core, as they are just two classes and has no dependencies. Let me know if that's acceptable.
PackageDownloader package file is in Packages/Tools directory and is loaded via an 'package autoload' menuitem in Open menu.
I haven't improved how the description of packages is shown in the tools as I forgot to do it before I'm making this pull request. I'll improve that next.
> Package Installer and Downloader integration

- Packages/AllPackages.pck.st
- Packages/TerseGuide.pck.st
- clonePackageRepos.sh
- pullAllRepos.sh
- statusAllRepos.sh
Elided deprecated packages and added UI packages.
Updated Color page in TerseGuide.
"Feature require: 'AllPackages'."   succeeds.
> Cuis-Smalltalk-UI support

- Packages/Tools/FlatFileList.pck.st
This fixes the world menu for FlatFileList tool.
> Fix FlatFileList world menu

- clonePackageRepos.sh
- pullAllRepos.sh
Would it be possible to add this package to the list?
> Add AnimatedGIF package to clonePackageRepos.sh

- Packages/Tools/ExamplesBrowser.pck.st
Can you merge please?
Adds syntax highlighting to ExamplesBrowser package and world menu fixes.
Thanks!
> ExamplesBrowser: syntax highlighting and world menu fix

- Packages/System/ExtendedClipboard.pck.st
Hi Juan,
With this change copying text in RTF format works again.
Cheers,
Bernhard
> Fix RTF clipboard

- Documentation/Technical/HitchHikersCompiler.md
the discussed Compile Time Evaluation construct's name is ##() - as per the original Vassili's article; it should not be confused with an array construct #()
> replace incorrect #() construct name references with correct ##() ones

- Documentation/CuisReleaseProcess.md
> Correct minor typo

- Packages/Features/Sound.pck.st
- Packages/System/Network-Kernel.pck.st
Update Network Package to Squeak 6.0-22148
This adds the newer network VM primitives and ipv6 logic.
Attempted to preserve original timestamps & original author code to make future code compares easier.
IPV6 support is off, future requirement to make that a image level preference
> Update Network Package to Squeak 6.0-22148
